image: node:latest

cache:
  paths:
    - node_modules/

variables:
  URL: "https://argoyal.gitlab.io"
  BASE_URL: "/anshulrgoyal/"


test_async:
  script:
    - npm i
    - npm run build


pages:
  script:
    - yarn install
    - yarn build
    - mv ./build ./public
  artifacts:
    paths:
      - public
  only:
    - master



